server {
  listen 80;
  server_name _;

  # Папка со статикой (куда мы скопировали dist)
  root /usr/share/nginx/html;
  index index.html;

  # SPA-роутинг: если файла нет — отдаём index.html
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Кэширование статики
  location ~* \.(?:js|css|png|jpg|jpeg|gif|svg|ico|webp|woff2?)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }
}
